spring:
  datasource:
    url: jdbc:tc:postgresql:16:///skill_platform
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  data:
    redis:
      host: localhost
      port: 6379

# Disable external services in test
minio:
  endpoint: http://localhost:9000

spring.elasticsearch.uris: http://localhost:9200
